towima/api/urls.py
from django.conf.urls import url, include
from django.urls import path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='Products')
router.register(r'categories', views.CategoryViewSet, basename='Categories')
router.register(r'comments', views.CommentsViewSet, basename='Comments')
router.register(r'ratings', views.RatingViewSet, basename='Ratings')
router.register(r'pharmacies', views.PharmacyViewSet, basename='Pharmacies')
router.register(r'users', views.UserViewSet, basename='Users')

app_name = 'api'
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

towima/orders/urls.py
from django.urls import path
from django.conf.urls import url
from orders import views

app_name = 'orders'
urlpatterns = [
    #path('create/', views.create_order, name='create'),  URL to create an order, currently not used.
]

towima/pharmacies/urls.py
from django.urls import path
from django.conf.urls import url
from pharmacies import views

app_name = 'pharmacies'
urlpatterns = [
    path('create_pharma/', views.create_pharma, name='create_pharma'),                                  # URL to create a pharmacy
    path('search/', views.search, name='search'),                                                       # URL to search a pharmacy
    url(r'^pharmacy/(?P<pk>\d+)/$', views.pharmacy, name='pharmacy'),                                   # URL to a pharmacy
    path('add_comment_to_pharmacy/', views.add_comment_to_pharmacy, name='add_comment_to_pharmacy'),    # URL to add a comment to a pharmacy
    path('add_rating_to_pharmacy/', views.add_rating_to_pharmacy, name='add_rating_to_pharmacy'),       # URL to add a rating to  a pharmacy
    path('product_detail/<pk>/<ppk>', views.product_detail, name='product_detail'),                     # URL to see a product of a pharmacy
    path('get_locations/', views.get_locations, name='get_locations'),                                  # URL to the location of a pharmacy
    path('pharma_settings/', views.pharma_settings, name='pharma_settings'),                            # URL to see the settings of a pharmacy
    path('orders/', views.pharmacy_orders, name='orders'),                                              # URL to see the orders of a pharmacy
    path('order_delete/<pk>', views.order_delete, name='order_delete'),                                 # URL to delete an order of a pharmacy
    path('confirm_order/<pk>', views.confirm_order, name='confirm_order'),                              # URL to fill an order of a pharmacy
    path('add_product/', views.add_product, name='add_product'),                                        # URL to add a product to a pharmacy
]

towima/towima/urls.py
# Necessary imports for the urls
from django.contrib import admin
from django.urls import path, include
from towima import views

urlpatterns = [
    path('', views.home, name='home'),                                  # The url for the homepage is empty
    path('admin/', admin.site.urls, name='admin'),                      # The url for the admin page
    path('accounts/', include('accounts.urls')),                        # This url pattern will be visitid for the signup and profile functionality
    path('accounts/', include('django.contrib.auth.urls')),             # The url where the accounts app runs
    path('pharmacies/', include('pharmacies.urls')),
    path('products/', include('products.urls', namespace='products')),  # The url where the products app is
    path('orders/', include('orders.urls', namespace='orders')),        # The url where the products app is
    path('api/', include('api.urls', namespace='urls')),   
]

towima/orders/models.py
from django.db import models
from products.models import Product
from pharmacies.models import Pharmacy
from django.contrib.auth.models import User
from pharmacies.models import Stock

class Other(models.Model):
    DEFAULT_PK=1
    name=models.CharField(max_length=1024)

# Definition of the model to save and order in the database. An order is placed by a customer and can be deleted by the user or pharmacist
# and be filled by the pharmacist if it is ready. The order constains the user that placed the order, the first name, the last name, the email
# the address, the product, the pharmacy, the price of the product, the quantity, the total price, field if the order is filled and dates 
# When the orders are created and updated. This model also contains a custom save function to calculate the total price and a function to get the price.
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=Other.DEFAULT_PK)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=True)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE, default=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    quantity = models.PositiveIntegerField(default=1)
    filled = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_price(self):
        return self.price * self.quantity

    def save(self, *args, **kwargs):
        stock_ = Stock.objects.get(product=self.product, pharmacy=self.pharmacy)
        self.unit_price = stock_.product_price
        self.total_price = self.unit_price * self.quantity
        super(Order, self).save(*args, **kwargs)
    

towima/pharmacies/models.py
from django.db import models
from django.urls import reverse
from products.models import Product
from django.contrib.auth.models import User
from django.utils import timezone

class Other(models.Model):
    DEFAULT_PK=1
    name=models.CharField(max_length=1024)

# Definition of the Pharmacy model. A pharmacy is created by a pharmacist.
class Pharmacy(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, default=Other.DEFAULT_PK) # Only one person can be the owner, and you can only own one pharmacy.
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    address = models.CharField(max_length = 50)
    phone_number = models.CharField(max_length=12)
    email = models.EmailField(default='example@example.com')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = models.ManyToManyField(Product, through='Stock', related_name="products+")
    pharmacists = models.ManyToManyField(User, through='Employee', related_name="pharmacists+")

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),) 

    def __str__(self):
        return self.name

    def get_absolute_url(self):
       return reverse('pharmacies:pharmacy', args=[self.pk])

# definition of a model to create a relation between a pharmacy and a pharmacist. This is usefull to add employees to the pharmacy.
# The relation contains the salary of the employee.
class Employee(models.Model):
    pharmacist = models.ForeignKey(User, on_delete=models.CASCADE)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)
    salary= models.PositiveIntegerField(default=0)

# Definition of a model to create a relation between a product and a pharmacy. A pharmacy can have multiple products and a product can be
# present in multiple pharmacies. The relation contains a price and an amount.
class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)
    product_stock = models.PositiveIntegerField(default=0)
    product_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

# The comment model. 
class Comments(models.Model):
    pharmacy = models.ForeignKey('Pharmacy', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

# The rating model. A rating has two foreign keys, namely the user that has posted the rating and the pharmacy that the rating is for.
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rating_user')
    pharmacy = models.ForeignKey('Pharmacy', on_delete=models.CASCADE, related_name='rated_user')
    rating = models.IntegerField()

towima/orders/forms.py
from django import forms
from .models import Order
from products.models import Product
from pharmacies.models import Pharmacy

 # Form to create a seperate order in the database. This is currently not used in our website, but not removed because it
 # is something that could be used on a later date.
class OrderForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField(label='E-Mail')
    product = forms.ModelChoiceField(queryset=Product.objects.all())
    pharmacy = forms.ModelChoiceField(queryset=Pharmacy.objects.all())
    address = forms.CharField()
    quantity = forms.IntegerField()

    class Meta:
        model = Order
        fields = (              # The order of the fields.
            'first_name', 
            'last_name', 
            'email',
            'address',
            'product',
            'pharmacy',
            'quantity',
        )

towima/pharmacies/forms.py
from django import forms
from pharmacies.models import Pharmacy, Comments, Stock
from products.models import Product
from accounts.models import Item
from django.contrib.auth.models import User

# Definition of the form the create a pharmacy. A pharmacy is created when a pharmacist does a sign up on the website. This also contains a
# custom save funtion for the Pharmacy to save the owner of the pharmacy (the currenlty logged in user).
class PharmacyForm(forms.ModelForm):
    name = forms.CharField(max_length = 70)
    email = forms.CharField(max_length = 50)
    phone_number = forms.CharField(max_length=12)
    address = forms.CharField(max_length = 50)
    
    
    class Meta:
        model = Pharmacy
        fields = ('name','address', 'email', 'phone_number')
        widgets = {'slug': forms.HiddenInput()}

    def save(self, user, commit = True):
        user_id = User.objects.get(username=user)
        name = self.cleaned_data['name']
        phone_number = self.cleaned_data['phone_number']
        address = self.cleaned_data['address']
        email = self.cleaned_data['email']
        if commit:         
            pharmacy = Pharmacy(owner=user_id, name=name, address=address, phone_number=phone_number, email=email)
            pharmacy.save()

# The comment form. This form has only one field, namely a text field.            
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('text',)

    # We created a custom save function, to correctly save the information in the database.
    def save(self, pk, user, commit = True):
        comment = super().save(commit=False)
        pharmacy = Pharmacy.objects.get(pk = pk)
        comment.pharmacy = pharmacy
        comment.author = user

        if commit:
            comment.save()
        return comment

# The add to cart form. This form has only one field, namely the quantity.
class AddToCartForm(forms.ModelForm):
    quantity = forms.IntegerField()

    class Meta:
        model = Item
        fields = (              # The order of the fields.
            'quantity',
        )

# Definition of the form to add stock and price of a certain product in the database to the pharmacy. The pharmacist needs to select
# a product and choose the amount in Stock and the price of the product in the pharmacy. This also contains a custom save function so there
# is only one relation between a product and a pharmcy, otherwise the current relation needs to be removed or modified.
class AddStockForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all())
    stock = forms.IntegerField()
    price = forms.DecimalField()

    class Meta:
        model = Stock
        fields = (              # The order of the fields.
            'product',
            'stock',
            'price',
        )
    def save(self, pharmacy, commit = True):
        product = self.cleaned_data['product']
        stock = self.cleaned_data['stock']
        price = self.cleaned_data['price']
        if commit:
            if not Stock.objects.filter(pharmacy=pharmacy, product=product):
                stock = Stock(product=product, pharmacy=pharmacy, product_stock=stock, product_price=price)
                stock.save()

towima/orders/views.py
from django.shortcuts import render, redirect
from pharmacies.models import Pharmacy
from .forms import OrderForm
from twilio.rest import Client

# View that is created for making a seperate order. There is also sms notification for the order to the pharmacy.
# This is currently not used in our website but is nog removed because it could be used in the furure if needed.
def create_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            user = request.user
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            product = form.cleaned_data.get('product')
            pharmacy = form.cleaned_data.get('pharmacy')
            address = form.cleaned_data.get('address')

            pharmacy_object = Pharmacy.objects.get(name=pharmacy)
            phone_number = pharmacy_object.phone_number
            print(phone_number)
            # Your Account SID from twilio.com/console
            account_sid = "ACb651004e985e1af070bb32fa81344449"
            # Your Auth Token from twilio.com/console
            auth_token  = "77ac7d6c5d77ea10284e2a61898aca64"

            client = Client(account_sid, auth_token)

            message = client.messages.create(
                to=phone_number, 
                from_="+32460201263",
                body="You have a new order!")

            return redirect('home')
    else:                                       
        form = OrderForm()
    form = OrderForm()
    return render(request, 'orders/order.html', {'form': form})

towima/templates/pharmacies/add_comment_to_pharmacy.html
{% extends 'base.html' %}

{% block content %}
    <h1 style="padding-top: 100px;">New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

towima/templates/pharmacies/add_product.html
{% extends 'base.html' %}
{% block title %}Add Product{% endblock %}

{% block content %}
<section id="signup_background">
        <section class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3 col-sm-12">
                    <div class="signup_card">
                        <h1> Add Product </h1>
    <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                      <div class="field">
                        <label for="{{ field.id_for_label }}" class="label">
                            {{ field.hyml_name }} 
                        </label>
                          <div class="row">
                              <div class="col-lg-5 col-md-12">
                                  <h4>{{ field.label_tag }}</h4>
                              </div>
                              <div class="col-lg-7 col-md-12">
                                  {{ field }}
                              </div>
                          </div>
                          <div class="row">
                              {% for error in field.errors %}
                                  <p style="color: red">{{ error }}</p>
                              {% endfor %}
                          </div> 
                      </div>
                    {% endfor %}
                    <br>
                        <button type="submit" class="btn btn-secondary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
</section>
{% endblock %}

towima/templates/pharmacies/orders.html
{% extends 'base.html' %}
{% block title %}Orders{% endblock %}

{% block content %}
<section class="container-fluid">
<h2>Open Orders</h2>
    <div class="row" style="text-align: center;">
        <div class="col">
            <h5>Product: </h5>
        </div>
        <div class="col">
            <h5>Pharmacy: </h5>
        </div>
        <div class="col">
            <h5>Total Price: </h5>
        </div>
        <div class="col">
            <h5>Date:</h5>
        </div>
        <div class="col">
            <h5>Fill Order:</h5>
        </div>
        <div class="col">
            <h5>Delete:</h5>
        </div>
        
    </div>
    <hr>
    {% for order in orders %}
        {% if order.filled == False %}
        <div class="row" style="text-align: center;">
            <div class="col">
                <p>{{order.product}}</p>
            </div>
            <div class="col">
                {{order.pharmacy}}
            </div>
            <div class="col">
                € {{order.unit_price}}
            </div>
            <div class="col">
                {{order.created}}
            </div>
            <div class="col">
                <a href="{% url 'pharmacies:confirm_order' order.pk %}">
                    <button type="button" class="btn btn-sm btn-dark" type="submit">Fill Order</button>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'order_delete' order.pk %}">
                    <button type="button" class="btn btn-sm btn-danger" type="submit">Delete</button>
                </a>
            </div>
        </div>
        <hr>
        {% endif %}
    {% endfor %}




<h2>Filled Orders</h2>
    <div class="row" style="text-align: center;">
        <div class="col">
            <h5>Customer:</h5>
        </div>
        <div class="col">
            <h5>Product: </h5>
        </div>
        <div class="col">
            <h5>Quantity:</h5>
        </div>
        <div class="col">
            <h5>Total Price: </h5>
        </div>
        <div class="col">
            <h5>Delete:</h5>
        </div>
    </div>
    <hr>
    {% for order in orders %}
    {% if order.filled == True %}
        <div class="row" style="text-align: center;">
            <div class="col">
                {{order.first_name}} {{order.last_name}}
            </div>
            <div class="col">
                <p>{{order.product}}</p>
            </div>
            <div class="col">
                {{order.pharmacy}}
            </div>
            <div class="col">
                € {{order.total_price}}
            </div>
            <div class="col">
                <a href="{% url 'pharmacies:order_delete' order.pk %}">
                    <button type="button" class="btn btn-sm btn-danger" type="submit">Delete</button>
                </a>
            </div>
        </div>
        <hr>
    {% endif %}
    {% endfor %}
</section>
{% endblock %}

towima/templates/pharmacies/pharmacy_profile.html
{% extends 'base.html' %}

{% block title %}Pharmacy Profile{% endblock %}

{% block content %}
<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .checked {
        color: orange;
    }
</style>

 <div class="background_pharmacy">
        <h1>{{ pharmacy.name}}</h1>
 </div>
<section class="container-fluid">
    <div class="row" style="text-align: center;">
        <div class="col-md-4 col-sm-12">
            <div class="row">
                <div class="col-12" id="profile_email"></div>
                <div class="col-12">
                    <br>
                    <h5>{{ pharmacy.email }}</h5>
                    <br>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12">
            <div class="row">
                <div class="col-12" id="profile_phone"> </div>
                <div class="col-12">
                    <br>
                    <h5>{{ pharmacy.phone_number }}</h5>
                    <br>
                </div>
            </div>
            
        </div>
        <div class="col-md-4 col-sm-12">
            <div class="row">
                <div class="col-12" id="profile_address"></div>
                <div class="col-12">
                    <br>
                    <h5>{{ pharmacy.address }}</h5>
                    <br>
                </div>
            </div>
        </div>
    </div>
    
<hr>

<h4>Available Products</h4>
    <div class="row">
        {% for stock in pharmacy_stock %}
        <div class="col-1"></div>
        <div class="col-lg-2 col-md-10 pharma_profile">
            <h4>{{stock.product}}</h4>
            <hr>
            <h6>€ {{stock.product_price}}</h6>
            <h6>{{stock.product.description}}</h6>
            <hr>
            <div class="btn_transition_pharma">
                <a id="btn_pharma" href="{% url 'pharmacies:product_detail' pk=pharmacy.pk ppk=stock.product.pk %}">
                   Order Now
                </a>
            </div>
        </div>
        <div class="col-1"></div>
        {% endfor %}
    </div>

<hr>
<h4>Rate This Pharmacy</h4>
    
<div class="rating">
    {% if rating %}
    {% for i in "12345" %}
    {% if rating >= forloop.counter %}
    <span onclick="add_rating({{ forloop.counter }})" class="fa fa-star checked"></span>
    {% else %}
    <span onclick="add_rating({{ forloop.counter }})" class="fa fa-star"></span>
    {% endif %}
    {% endfor %}
    {% else %}
    <div id="strong"><strong>This pharmacy has not been rated yet. Be the first to rate them!</strong><br></div>
    {% for i in "12345" %}
    <span onclick="add_rating({{ forloop.counter }})" class="fa fa-star"></span>
    {% endfor %}
    {% endif %}
</div>
<br>
<a class="btn btn-secondary" data-toggle="collapse" href="#commentCollapse" role="button" aria-expanded="false" aria-controls="commentCollapse">Add comment</a>    
<div class="collapse multi-collapse" id="commentCollapse">
    <div class="card card-body">
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-secondary" id="commentSubmit">Send</button>
        </form>
    </div>
</div>
<hr>
<h4>Comments</h4>
<div class="comments" style="text-align: center;">
{% for comment in pharmacy.comments.all %}
<div class="comment">
    <strong>{{ comment.author }}</strong>
    <div class="date">{{ comment.created_date }}</div>
    <p>{{ comment.text|linebreaks }}</p>
    <br>
</div>
{% endfor %}

</div>
</section>
{% endblock %}

{% block javascript %}
<script>
    const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"];
    function add_rating(new_rating) {
        $.ajax({
            url: "{% url 'pharmacies:add_rating_to_pharmacy' %}",
            data: {
                'pk': "{{ pharmacy.pk }}",
                'new_rating': new_rating
            },
            dataType: 'json',
            success: function (data) {
                $("#strong").remove();
                var rating = data.old_rating;
                var new_rating = data.new_rating;
                var difference = new_rating - rating;
                if (difference > 0){
                    for(var i = new_rating; i >= rating; i--){
                        $('.rating span:eq(' + (i-1) + ')').replaceWith('<span onclick="add_rating(' + i + ')" class="fa fa-star checked"></span>');
                    }
                }else if (difference < 0){
                    for(var i = rating; i > new_rating; i--){
                        $('.rating span:eq(' + (i-1) + ')').replaceWith('<span onclick="add_rating(' + i + ')" class="fa fa-star"></span>');
                    }
                }
                
            }
      });

    };

    $( "#commentSubmit" ).click(function( event ) {
        event.preventDefault();
        $.ajax({
            url: "{% url 'pharmacies:add_comment_to_pharmacy' %}",
            type: 'post',
            dataType: 'json',
            data: {
                'csrfmiddlewaretoken': "{{ csrf_token }}",
                'pharmacy': "{{ pharmacy.pk }}",
                'text': $('#id_text').val(),
            },
            success: function(data) {
                if (data.valid){
                    $('#id_text').val('');
                    $(".collapse").collapse('hide');
                    var author = data.author;
                    var text = data.text;
                    var date = new Date(data.date);
                    var day = date.getDate();
                    var month = monthNames[date.getMonth()];
                    var year = date.getFullYear();
                    var hours = date.getHours() - 1; // Server is one hour behind.
                    var minutes = date.getMinutes();
                    var ampm = hours >= 12 ? 'p.m.' : 'a.m.';
                    hours = hours % 12;
                    hours = hours ? hours : 12; // the hour '0' should be '12'
                    minutes = minutes < 10 ? '0'+minutes : minutes;
                    formattedDate = day + ' ' + month + ' ' + year + ', ' + hours + ':' + minutes + ' ' + ampm;
                    $(".comments").append('<div class="comment"><div class="date">'+ formattedDate +'</div><strong>'+ author +'</strong><p>'+ text +'</p></div>');;
                }else{
                    alert("The form was invalid. Try again!");
                }
            },
            error:function(error){
                alert("Something went wrong. Try again!");
            }
        });
    });

</script>
{% endblock %}

towima/templates/pharmacies/search.html
{% extends 'base.html' %}
{% block title %}Search results{% endblock %}

{% block content %}
<section class="container-fluid" style="padding-top: 2vh;">
    <h2>Search Results</h2>
    <p>
    {% if num_results == 1 %}
    1 result for {{ query }} in {{ time }} seconds.
    {% else %}
    {{ num_results }} results for {{ query }} in {{ time }} seconds.
    {% endif %}
    </p>
    <div class="row">
        {% for pharmacy in results %}
            <div class="col-1"></div>
            <div class="col-lg-2 col-md-10 search_card">
                <a id="search_result" href= "{% url 'pharmacies:pharmacy' pk=pharmacy.pk %}">
                    <h4>{{pharmacy.name}}</h4>
                    <div class="row search_row">
                        <div class="col-3 search_map"></div>
                        <div class="col-9 search-text"><p>{{pharmacy.address}}</p></div>
                    </div>
                    <br>
                    <div class="row search_row">
                        <div class="col-3 search_phone"></div>
                        <div class="col-9 search-text"><p>{{pharmacy.phone_number}}</p></div>
                    </div>
                </a> 
            </div>
            <div class="col-1"></div>
         {% endfor %}
    </div>
</section>
<hr>
<section class="container-fluid" style="padding-top: 2vh;">
    <h2>Find your local pharmacy</h2>
        <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.3.0/mapbox-gl-geocoder.min.js'></script>
            <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.3.0/mapbox-gl-geocoder.css'
                type='text/css' />
            <div id='map' style='width: 100%; height: 500px; border-radius: 20px;'></div>

            <script>
                mapboxgl.accessToken = 'pk.eyJ1IjoibWF4aW1lYW50b2luZTE5OTciLCJhIjoiY2pubTNmNmlrMWpvdjNxdGFsdGxxaXJlayJ9.0tDqrdUlSYEOqxMSiy7j3g';
                var map = new mapboxgl.Map({
                    container: 'map',
                    style: 'mapbox://styles/mapbox/streets-v10',
                    center: [4.395907, 50.821190],
                    zoom: 10
                });

                // Add search bar to the map.
                map.addControl(new MapboxGeocoder({
                    accessToken: mapboxgl.accessToken
                }));

                // Add zoom and rotation controls to the map.  
                map.addControl(new mapboxgl.NavigationControl());
                // Add geolocate control to the map.
                map.addControl(new mapboxgl.GeolocateControl({
                    positionOptions: {
                        enableHighAccuracy: true
                    },
                    trackUserLocation: true
                }));

                var geojson = (function () {
                    var json = null;
                    $.ajax({
                        'async': false,
                        'global': false,
                        'url': "{% url 'pharmacies:get_locations' %}",
                        'dataType': "json",
                        'success': function (data) {
                            json = data;
                        }
                    });
                    return json;
                })();

                // add markers to map
                geojson.features.forEach(function (marker) {

                    // create a HTML element for each feature
                    var el = document.createElement('div');
                    el.className = 'marker';
                    var pk = marker.properties.description;
                    var title = marker.properties.title
                    var link = '<a id="mb_pop" href="{% url 'pharmacies:pharmacy' 1234 %}">' + title + '</a>';
                    link = link.replace(/1234/, pk);
                    // make a marker for each feature and add to the map
                    new mapboxgl.Marker(el)
                        .setLngLat(marker.geometry.coordinates)
                        .setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
                        .setHTML(link))
                        .addTo(map);
                });
        </script>
    <br><br>
{% endblock %}