towima/api/urls.py
from django.conf.urls import url, include
from django.urls import path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet, basename='Products')
router.register(r'categories', views.CategoryViewSet, basename='Categories')
router.register(r'comments', views.CommentsViewSet, basename='Comments')
router.register(r'ratings', views.RatingViewSet, basename='Ratings')
router.register(r'pharmacies', views.PharmacyViewSet, basename='Pharmacies')
router.register(r'users', views.UserViewSet, basename='Users')

app_name = 'api'
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

towima/pharmacies/urls.py
from django.urls import path
from django.conf.urls import url
from pharmacies import views

app_name = 'pharmacies'
urlpatterns = [
    path('create_pharma/', views.create_pharma, name='create_pharma'),                                  # URL to create a pharmacy
    path('search/', views.search, name='search'),                                                       # URL to search a pharmacy
    url(r'^pharmacy/(?P<pk>\d+)/$', views.pharmacy, name='pharmacy'),                                   # URL to a pharmacy
    path('add_comment_to_pharmacy/', views.add_comment_to_pharmacy, name='add_comment_to_pharmacy'),    # URL to add a comment to a pharmacy
    path('add_rating_to_pharmacy/', views.add_rating_to_pharmacy, name='add_rating_to_pharmacy'),       # URL to add a rating to  a pharmacy
    path('product_detail/<pk>/<ppk>', views.product_detail, name='product_detail'),                     # URL to see a product of a pharmacy
    path('get_locations/', views.get_locations, name='get_locations'),                                  # URL to the location of a pharmacy
    path('pharma_settings/', views.pharma_settings, name='pharma_settings'),                            # URL to see the settings of a pharmacy
    path('orders/', views.pharmacy_orders, name='orders'),                                              # URL to see the orders of a pharmacy
    path('order_delete/<pk>', views.order_delete, name='order_delete'),                                 # URL to delete an order of a pharmacy
    path('confirm_order/<pk>', views.confirm_order, name='confirm_order'),                              # URL to fill an order of a pharmacy
    path('add_product/', views.add_product, name='add_product'),                                        # URL to add a product to a pharmacy
]

towima/towima/urls.py
# Necessary imports for the urls
from django.contrib import admin
from django.urls import path, include
from towima import views

urlpatterns = [
    path('', views.home, name='home'),                                  # The url for the homepage is empty
    path('admin/', admin.site.urls, name='admin'),                      # The url for the admin page
    path('accounts/', include('accounts.urls')),                        # This url pattern will be visitid for the signup and profile functionality
    path('accounts/', include('django.contrib.auth.urls')),             # The url where the accounts app runs
    path('pharmacies/', include('pharmacies.urls')),
    path('products/', include('products.urls', namespace='products')),  # The url where the products app is
    path('orders/', include('orders.urls', namespace='orders')),        # The url where the products app is
    path('api/', include('api.urls', namespace='urls')),   
]

towima/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <!-- BOOTSTRAP library -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href='{% static "css/styles.css" %}'>
    <!-- JQUERY library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- MapBox libraries -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.css' rel='stylesheet' />
    <title>{% block title %}Towima pharma service{% endblock %}</title>   
  </head>
  
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'home' %}">
              <img src="{% static '../static/media/logo2.svg' %}" width="130" height="26" class="d-inline-block align-top"alt="">
            </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavbarHeader" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse " id="NavbarHeader">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <form class="form-inline" id="searchform" action="{% url 'pharmacies:search' %}" method="get" accept-charset="utf-8">
                      <a href="{% url 'pharmacies:search' %}" id="base_search"> 
                         <i class="fa fa-search text-black ml-3 active" aria-hidden="true"></i>
                      </a>
                      <input class="form-control form-control-sm ml-3 w-75" type="text" placeholder="Search" aria-label="Search" id="searchbox" name="q" type="text">
                    </form>
                {% endif %}
            </ul>
            <ul class="navbar-nav justify-content-end">
                {% if user.is_authenticated %}
                    {% if user.profile.user_type == "Pharmacist" %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pharmacy</a>
                      <div class="dropdown-menu bg-light dropdown-menu-right" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href="{% url 'pharmacies:add_product' %}">Add product</a> 
                        <a class="dropdown-item" href="{% url 'pharmacies:orders' %}">Orders</a>
                      </div>
                    </li> 
                    {% endif %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.username }}</a>
                      <div class="dropdown-menu bg-light dropdown-menu-right" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'orders' %}">Orders</a> 
                        <a class="dropdown-item" href="{% url 'edit' %}">Edit Profile</a>
                        <a class="dropdown-item" href="{% url 'change-password' %}">Change Password</a>  
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>  
                      </div>
                    </li>
                     {% if user.profile.user_type == "Customer" %}
                    <li class="nav-item"> 
                        <a class="nav-link" href="{% url 'cart' %}">
                            <img src="{% static "../static/media/frontpage/cart_black.svg" %}" width="20px" height="20px;" style="margin-top: 3px;" class="d-inline-block align-top" alt=""> 
                            Cart
                        </a>
                    </li>
                    {% endif %}
                  {% else %}
                     <li class="nav-item"><a  class="nav-link" href="{% url 'login' %}">Login</a></li>
                     <li class="nav-item"><a  class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                  {% endif %}
            </ul>
          </div>
        </nav>
    </header>
    
    <main>
      {% block content %}
      {% endblock %}
    </main>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> 
      {% block javascript %}{% endblock %}
  </body>
</html>

towima/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div id="home">
            <div class="landing-text">
                <h1>PHARMATOWI</h1>
                <h3>An online platform to order and connect with your local pharmacies</h3>
            </div>
    </div>
    <div class="btn_transition">
        <a href="#our_mission" class="btn2 scrollLink">Learn More</a>
    </div>
<br><br><br><br><br><br><br><br>
<div class="container-fluid mission" id="our_mission" style="padding-top: 20px; min-height: 300px;">
    <h1 style="font-weight: bold">Our Mission</h1>
    <div class="row">
        <div class="col-8">
            <p>Our goal is to close the gap between customers and their pharmacists. We try to achieve this by speeding up the process of ordering and communicating between one another. By doing this, customers don't have to wait at the pharmacy anymore and pharmacists can speed up their workflow.  </p>
        </div>
        <div class="col-4 about_us_img">
        </div>
        
    </div>
    
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col tab1">
            
        </div>
        <div class="col tabs_text">
            <h2>Order</h2>
            <p>Place your order online and get notified when it's ready!</p>
        </div> 
    </div> 
</div>
<br><br>
<div class="container-fluid">
    <div class="row">
        <div class="col tab2">
            
        </div>
        <div class="col tabs_text">
            <h2>Talk</h2>
            <p>Talk to your pharmacist and get some advice.</p>
        </div> 
    </div>
</div>
<br><br>
<div class="container-fluid">
    <div class="row">
        <div class="col tab3">
            
        </div>
        <div class="col tabs_text">
            <h2>Find your local pharmacy</h2>
            <p>Know where your nearest pharamcy is</p>
        </div> 
    </div>
</div>
<br><br>
<div class="container">
    <div class="row">
        <div class="col-6 supplement"> 
        </div>
        <div class="col-6 wannajoin">
            <div class="join_text">
                <h1>Get Started</h1>
                <h3>Sign up now and get access to hundreds of pharmacies!</h3>
            </div>
            <div class="btn_transition1">
                <a class="btn1" href="{% url 'signup' %}">Sign Up</a>
            </div>
            
        </div>
    </div>

</div>


<br><br><br><br><br><br>
<br><br>
<script>
    $(document).ready(function(){
    $( "a.scrollLink" ).click(function( event ) {
        event.preventDefault();
        $("html, body").animate({ scrollTop: $($(this).attr("href")).offset().top }, 500);
    });
});
</script>

{% endblock %}